defaults: &defaults
  adapter: sqlite

development:
  database: db/development.sqlite3
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/test.sqlite3
  <<: *defaults
production:
  database: db/production.sqlite3
  #database: db/ihub_production.db
  <<: *defaults
